labels:
  - name: "bug"
    color: "d73a4a"
    description: "Something isn't working"

  - name: "build"
    color: "1d76db"
    description: "Package build changes"

  - name: "ci"
    color: "0e8a16"
    description: "Changes to CI"

  - name: "documentation"
    color: "0075ca"
    description: "Improvements or additions to documentation"

  - name: "duplicate"
    color: "cfd3d7"
    description: "This issue or pull request already exists"

  - name: "good first issue"
    color: "7057ff"
    description: "Good for newcomers"

  - name: "help wanted"
    color: "008672"
    description: "Extra attention is needed"

  - name: "question"
    color: "cc317c"
    description: "Further information is requested"

  - name: "source"
    color: "00a4ff"
    description: "Source code change (releasable)"

  - name: "stale"
    color: "8b4513"
    description: "Pull request has no activity"

  - name: "test"
    color: "00b000"
    description: "Changing the test suite"

  - name: "tools"
    color: "DE0531"
    description: "Changes to any of the tooling"

  - name: "wontfix"
    color: "ffffff"
    description: "This will not be worked on"
