services:
  pubsub-emulator:
    image: google/cloud-sdk:latest@sha256:f91af03cbea86d4bd549ea070d3847478da0faac5bdb7b7675ab8b3cd50b19da
    command: gcloud beta emulators pubsub start --project=pytest-streaming --host-port=0.0.0.0:8432
    ports: ['8432:8432']
    environment:
      PUBSUB_PROJECT_ID: pytest-streaming
      PUBSUB_EMULATOR_HOST: localhost:8432
  pulsar:
    image: apachepulsar/pulsar:4.2.4@sha256:cd5d4a64a32c0770d5d2dbb526169a70081605bbec4b59b73471b68d0a451fb4
    container_name: pulsar
    ports: ['6650:6650', '8080:8080']
    environment:
    - PULSAR_STANDALONE_ENABLED=true
    - allowAutoTopicCreation=true
    command: [bin/pulsar, standalone]
