services:
  pubsub-emulator:
    image: google/cloud-sdk:latest@sha256:96a99902b17be6192e01bd94067d72e9c1c017a042ad970e98eb576070562058
    command: gcloud beta emulators pubsub start --project=pytest-streaming --host-port=0.0.0.0:8432
    ports: ['8432:8432']
    environment:
      PUBSUB_PROJECT_ID: pytest-streaming
      PUBSUB_EMULATOR_HOST: localhost:8432
  pulsar:
    image: apachepulsar/pulsar:4.2.3@sha256:71b014dd8a841469ad8f6c92053affdbc4b4a55361be919722d0c4896b480f39
    container_name: pulsar
    ports: ['6650:6650', '8080:8080']
    environment:
    - PULSAR_STANDALONE_ENABLED=true
    - allowAutoTopicCreation=true
    command: [bin/pulsar, standalone]
