name: check for stale pull requests
on:
  schedule:
  - cron: 0 1 */14 * *
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9
      with:
        days-before-pr-stale: 60
        days-before-pr-close: 60
        stale-pr-label: stale
        remove-stale-when-updated: 'true'
