name: validate pr title

on:
  pull_request:
    branches:
      - main
    types:
      - edited
      - labeled
      - opened
      - reopened
      - synchronize
      - unlabeled
  workflow_dispatch:

jobs:
  main:
    name: validate pr title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}