name: release
on:
  push:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      with:
        persist-credentials: false
    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: 22
    - uses: jdx/mise-action@13abe502c30c1559a5c37dff303831bab82c9402 # v2
      with:
        cache: true
    - name: Dependency cache
      id: cache
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: .venv
        key: ${{ runner.os }}-release-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-release-${{ hashFiles('**/pyproject.toml') }}
    - name: install semantic-release and plugins
      run: |
        npm install -g semantic-release \
          @semantic-release/changelog \
          @semantic-release/git \
          semantic-release-pypi
    - name: run semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: semantic-release --branches main
