# https://github.com/suzuki-shunsuke/github-action-renovate-config-validator
name: renovate-config-validator

on:
  pull_request:
    branches:
    - main
    paths:
    - renovate.json
  push:
    branches:
    - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1