---
name: yml lint
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  yml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          cache: true
      - name: Dependency cache
        id: cache
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-yml-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-yml-${{ hashFiles('**/pyproject.toml') }}
      - name: run yml lint
        run: |-
          just yml-check
